// src/app/layout.js
import './globals.css';
import 'leaflet/dist/leaflet.css';
import ClientLayout from '@/components/ClientLayout';

export const metadata = {
  title: 'My Map App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
