// src/app/layout.js
import './globals.css';
import 'leaflet/dist/leaflet.css'; // <-- Add this line

export const metadata = {
  title: 'My Map App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* We'll add the main layout structure later */}
        {children}
      </body>
    </html>
  );
}